### ISSUE TITLE
Help Bug :S

### ISSUE THREAD

**Issue by DiornanR** [nightw0lv/VDSystem#3]
Good morning dear, I am having a small problem with the keys that Hopzone generates when adding it, as well as topGS and L2JBrasil.

ApiKey Hopzone.net: HopzoneApiKey =jdOS4LAa2L7jNKh9peGqxjNmN
![imagen_2024-01-22_080930059](https://github.com/nightw0lv/VDSystem/assets/104043687/71f98625-cd4c-427e-80f6-938a71516475)

ApiKey TopGS: L2TopGSApiKey =NTE1TGluZWFnZSAyIFJFREM0NjVhZGMzYjFhYmY0Mw==
ApliKey L2JBrasil =WarderS
Console error
Error: Server returned HTTP response code: 403 for URL: https://l2.topgameserver.net/lineage/VoteApi/API_KEY=NTE1TGluZWFnZSAyIFJFREM0NjVhZGMzYjFhYmY0Mw==/getData
![imagen_2024-01-22_080326612](https://github.com/nightw0lv/VDSystem/assets/104043687/087c3c0c-a0f5-491d-adba-5cff8c0620a0)

**Comment by nightw0lv** [comment]
About l2.topgameserver.net you have to contact the admin.
About l2jbrasil I am not sure they fixed their api
About hopzone.net https://api.hopzone.net/lineage2/vote?token=jdOS4LAa2L7jNKh9peGqxjNmN&ip_address=1.1.1.1
replace 1.1.1.1 with your ip and check for your self if works and returns voted: true then the problem is something else
Try to register in hopzone.eu

Let me know of the results

**Comment by DiornanR** [comment]
perfect, I just carried out the check with the specifications that you have provided me, I have already sent a statement to TopGS and others to see what resolution they have, something else this this detail

java.time.format.DateTimeParseException: Text 'NONE' could not be parsed at index 0
        at java.time.format.DateTimeFormatter.parseResolved0(Unknown Source)
        at java.time.format.DateTimeFormatter.parse(Unknown Source)
        at java.time.LocalDateTime.parse(Unknown Source)
        at hopzone.eu.util.Utilities.millisecondsFromString(Utilities.java:389)
        at hopzone.eu.model.IndividualResponse.onFetch(IndividualResponse.java:118)
        at hopzone.eu.model.base.IResponse.connect(IResponse.java:133)
        at hopzone.eu.model.IndividualResponse.connect(IndividualResponse.java:150)
        at hopzone.eu.command.VoteCMD.Execute(VoteCMD.java:351)
        at hopzone.eu.command.VoteCMD.lambda$useVoicedCommand$3(VoteCMD.java:229)
        at hopzone.eu.util.VDSThreadPool$TaskWrapper.run(VDSThreadPool.java:138)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.time.format.DateTimeParseException: Text 'NONE' could not be parsed at index 0
        at java.time.format.DateTimeFormatter.parseResolved0(Unknown Source)
        at java.time.format.DateTimeFormatter.parse(Unknown Source)
        at java.time.LocalDateTime.parse(Unknown Source)
        at hopzone.eu.util.Utilities.millisecondsFromString(Utilities.java:389)
        at hopzone.eu.model.IndividualResponse.onFetch(IndividualResponse.java:119)
        at hopzone.eu.model.base.IResponse.connect(IResponse.java:133)
        at hopzone.eu.model.IndividualResponse.connect(IndividualResponse.java:150)
        at hopzone.eu.command.VoteCMD.Execute(VoteCMD.java:351)
        at hopzone.eu.command.VoteCMD.lambda$useVoicedCommand$3(VoteCMD.java:229)
        at hopzone.eu.util.VDSThreadPool$TaskWrapper.run(VDSThreadPool.java:138)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by nightw0lv** [comment]
weird the only NONE text i know of existance is this 
https://github.com/nightw0lv/VDSystem/blob/master/Interlude/aCis/config/VDSystem.properties
line 465
but what this has to do with the datetime is a good question
 
so my question is what you do before you get this error? try to vote individual at top.4teambr.com?

a possible solution is to try and disable all votes and enable 1 by 1

**Comment by DiornanR** [comment]
> weird the only NONE text i know of existance is this https://github.com/nightw0lv/VDSystem/blob/master/Interlude/aCis/config/VDSystem.properties line 465 but what this has to do with the datetime is a good question
> 
> so my question is what you do before you get this error? try to vote individual at top.4teambr.com?
> 
> a possible solution is to try and disable all votes and enable 1 by 1

I did not have to send a message to the development teams of the various voting platforms to check, Now regarding that error, I have already checked the solution that was given to me.

**Comment by nordbit** [comment]
> voted: true
There is no "voted"
https://hopzone.eu/docs.html/

**Comment by nordbit** [comment]
>voted: true

There is no "voted"
https://hopzone.eu/docs.html/

**Comment by nightw0lv** [comment]
> > voted: true
> 
> There is no "voted" https://hopzone.eu/docs.html/

in hopzone.net
voted: true
https://api.hopzone.net/lineage2/vote?token=jdOS4LAa2L7jNKh9peGqxjNmN&ip_address=1.1.1.1

in hopzone.eu
status: "completed"
https://api.hopzone.eu/v1/?api_key=iaFQIc7E6f1d8D2wvXxUL4n5q&ip=1.1.1.1&type=json

**Comment by nordbit** [comment]
whatever

Game server is registered on the toplists, api keys are putted in config, APIs are tested and voting works on all topsites
l2jBrasil API (they have any?) is broken from owner of the toplist side.
Only iTopZ is working, rest of toplists no, hopezone.eu crashing player client.
Probably VDSystem trying to send incorrect parsed data from json response
Here is hint from report above:

> java.time.format.DateTimeParseException: Text 'NONE' could not be parsed at index 0
