### ISSUE TITLE
MAC error?

### ISSUE THREAD

**Issue by Her0ic96** [nightw0lv/VDSystem#4]
I trying test this system and i have problem:

2024.07.09 20:39:15,001	WARNING	143	org.l2jmobius.gameserver.network.PacketLogger	Client: [Character: ADMINHER0ic[268513914] - Account: her0ic - IP: 127.0.0.1] - Failed running: Say2 ; Cannot invoke "org.l2jmobius.gameserver.model.holders.ClientHardwareInfoHolder.getMacAddress()" because the return value of "org.l2jmobius.gameserver.network.GameClient.getHardwareInfo()" is null
2024.07.09 20:39:15,001	WARNING	143	org.l2jmobius.gameserver.network.PacketLogger	java.lang.NullPointerException: Cannot invoke "org.l2jmobius.gameserver.model.holders.ClientHardwareInfoHolder.getMacAddress()" because the return value of "org.l2jmobius.gameserver.network.GameClient.getHardwareInfo()" is null
	at hopzone.eu.command.VoteCMD$FloodProtectorHolder.<init>(VoteCMD.java:122)
	at hopzone.eu.command.VoteCMD.lambda$getFloodProtector$1(VoteCMD.java:98)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at hopzone.eu.command.VoteCMD.getFloodProtector(VoteCMD.java:96)
	at hopzone.eu.command.VoteCMD.useVoicedCommand(VoteCMD.java:190)
	at handlers.chathandlers.ChatGeneral.handleChat(ChatGeneral.java:67)
	at org.l2jmobius.gameserver.network.clientpackets.Say2.runImpl(Say2.java:226)
	at org.l2jmobius.gameserver.network.clientpackets.ClientPacket.run(ClientPacket.java:53)
	at org.l2jmobius.commons.threads.RunnableWrapper.run(RunnableWrapper.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)

**Comment by nightw0lv** [comment]
its because the HWID is null, it is probably because you are testing in local without client protection like smartguard or aac

**Comment by Her0ic96** [comment]
yes i realized that but can you make a branch for this?

**Comment by nightw0lv** [comment]
> yes i realized that but can you make a branch for this?

at the moment i do not have the time for this because it involves all the projects, new releases for each project, new documentation maybe on the winter but it will be very confuzing, it is very easy to remove the HWID instead from the checking on VDSystem command under the package `hopzone.eu.command.VoteCMD.java` and ignore that or simply set it as "" (empty string) or the players name on line 122 and everywhere i the code asking .getHardwareInfo() function

**Comment by Her0ic96** [comment]
sure but can you give me links for how to complice your source?

**Comment by Her0ic96** [comment]
E:\L2j-Cloud\VDS\Mobius\L2J_Mobius_11.0_TheSourceOfFlame\src\hopzone\eu\command\VoteCMD.java:29:37
java: package org.l2jmobius.gameserver.data does not exist but i 

![image](https://github.com/user-attachments/assets/58b9642e-02c0-4b09-815f-ee76349394ee)

**Comment by nightw0lv** [comment]
you just build the project and everything goes in the out folder.
just fix paths for java and install the java versions
to build one project you need to add the libraries
make a "lib" folder and include it as library on the project you want to build
